name: "Client Tests"
on: [push, pull_request]
jobs:

  test-client-ubuntu:
    name: "Client Tests"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]

    steps:

      - name: Set up Go 1.14
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.14
        id: go

      - name: Checkout
        uses: actions/checkout@v2

      - name: Test client
        run: |
          go test -v ./... --check.v
